version: '3.7'

services:
    nginx:
        build:
            context: ./web
            dockerfile: Dockerfile.prod
        image: nginx:prod
        container_name: nginx
        restart: always
        ports: 
            - "80:80"
        depends_on: 
            - api
        networks:
            - frontend
    db:
        image: mysql/mysql-server:5.7
        container_name: db
        restart: always
        environment:
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_DATABASE
            - MYSQL_ALLOW_EMPTY_PASSWORD
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - "db:/var/lib/mysql"
        networks:
            - backend
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
            args:
                UID: ${UID}
                GID: ${GID}
        image: api:prod
        container_name: api
        restart: always
        env_file: ./api/.env.dev
        command: gunicorn --bind 0.0.0.0:5000 --chdir src main:app
        volumes: 
            - "./api:/home/default/api"
        ports: 
            - "5000:5000"
        depends_on: 
            - db
        networks: 
            - backend

networks:
    backend:
    frontend:

volumes:
    db:
