version: '3.7'

services:
  db:
    image: mysql/mysql-server:5.7
    container_name: db
    restart: always
    volumes: 
      - "/var/lib/docker/volumes/455163fdef4072553c8d8303d53292431c2696a2c61f3f2137e3eca65d5b233d/_data:/var/lib/mysql"
    networks: 
      - backend
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
      args:
        UID: ${UID}
        GID: ${GID}
    image: api:dev
    container_name: api
    restart: always
    env_file: ./api/.env.dev
    volumes: 
      - "./api:/home/default/api"
    ports: 
      - "5000:5000"
    depends_on: 
      - db
    networks: 
      - backend
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    image: web:dev
    container_name: web
    restart: always
    volumes:
      - "./web:/home/node/web"
    ports:
      - "8080:8080"
    networks: 
      - frontend
    depends_on: 
      - api

networks:
  frontend:
  backend: