version: '3.7'

services:
  db:
    image: mysql/mysql-server:5.7
    container_name: db
    restart: always
    volumes: 
      - "spending-journal:/var/lib/mysql"
    networks: 
      - backend
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    image: api:dev
    container_name: api
    restart: always
    env_file: ./api/.env.dev
    volumes: 
      - "./api:/home/default/api"
    ports: 
      - "5000:5000"
    command: flask run --host=0.0.0.0
    depends_on: 
      - db
    networks: 
      - backend
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    image: web:dev
    container_name: web
    restart: always
    volumes:
      - "./web:/home/node/web"
    ports:
      - "8080:8080"
    networks: 
      - frontend
    depends_on: 
      - api

volumes: 
  spending-journal:
      external: true

networks:
  frontend:
  backend: