version: '3.7'

services:
    front-end:
        image: spendingjournal/front-end:prod
        container_name: nginx
        restart: always
        ports: 
            - "80:80"
        depends_on: 
            - api
        networks:
            - frontend
    db:
        image: mysql/mysql-server:5.7
        container_name: db
        restart: always
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - "spending-journal:/var/lib/mysql"
        networks:
            - backend
    api:
        image: spendingjournal/back-end:prod
        container_name: api
        restart: always
        env_file: ./api/.env.dev
        command: gunicorn --bind 0.0.0.0:5000 --chdir src main:app
        volumes: 
            - "./api:/home/default/api"
        ports: 
            - "5000:5000"
        depends_on: 
            - db
        networks: 
            - backend

networks:
    backend:
    frontend:

volumes:
    spending-journal:
        external: true
