version: '3.7'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
      args:
        UID: ${UID}
        GID: ${GID}
    image: api:dev
    container_name: api
    restart: always
    env_file: ./api/.env.dev
    volumes: 
      - "./api:/home/default/api"
    ports: 
      - "5000:5000"
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    image: web:dev
    container_name: web
    restart: always
    volumes:
      - "./web:/home/node/web"
    ports:
      - "8080:8080"
    networks: 
      - frontend
    depends_on: 
      - api

networks:
  frontend:
  default:
    external:
      name: my-net