version: '3.7'

services:
    front-end:
        image: spendingjournal/web:production
        container_name: nginx
        restart: always
        ports: 
            - "80:80"
        depends_on: 
            - api
        networks:
            - front-end
    db:
        image: mysql/mysql-server:5.7
        container_name: db
        restart: always
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        networks:
            - back-end
        environment:
            MYSQL_ROOT_PASSWORD: rootroot
            MYSQL_DATABASE: mydb
            MYSQL_USER: root
            MYSQL_PASSWORD: rootroot
    api:
        image: spendingjournal/api:production
        container_name: api
        restart: always
        env_file: ./api/.env.production
        ports:
            - "5000:5000"
        depends_on: 
            - db
        networks: 
            - back-end


networks:
    back-end:
    front-end:
