###########################################################
#
# This playbook works side by side with the Terraform 
# template ec2.tf, which also locates under this folder, 
# to provision EC2 instancces created using that ec2.tf.
#
# In that, it installs required packages (including docker,
# docker SDK for Python) for the Ansible docker_container 
# module.
#
###########################################################
---
- name: EC2 setup
  hosts: all
  become: True
  tasks:
  - name: Check if cache is out of date and redownload if needed
    yum:
      update_cache: yes
      name: '*'
      state: latest
  - name: Install the most recent Docker Community Edition package
    shell: "amazon-linux-extras install docker"
  - name: Start Docker service and enable it at startup.
    service:
      name: docker
      state: started
      enabled: yes

    # Docker SDK for Python installation is done via the pip module
  - name: Update the package index, and install required package(s) for pip module
    yum: 
      update_cache: yes
      name: python-pip
      state: latest
  - name: Install Docker SDK for Python
    pip:
      name: docker