"""empty message

Revision ID: 82786e253848
Revises: 3dbf6bff0c3a
Create Date: 2020-04-01 16:02:55.047960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82786e253848'
down_revision = '3dbf6bff0c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'picture_url',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['picture_url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'picture_url',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###
